baseURL = "https://geisterbaustellen.de/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableKinds = ["taxonomy", "term", "RSS"]

[languages]
  [languages.de]
    locale = "de-DE"
    title = "Berlins älteste offene Baustellen"
    weight = 1
  [languages.en]
    locale = "en-GB"
    title = "Berlin's oldest open construction sites"
    weight = 2
